=== InvokerSoloMid/Kawaii/MyXMLSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="https://www.w3schools.com"
    elementFormDefault="qualified"
    xmlns="https://www.w3schools.com"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="USERS-DOCUMENTS-CHANGE_HISTORY-OFFLINE_PRESENTATION">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="USERS" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
        <xs:element name="USER" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="NAME">
                <xs:complexType>
                  <xs:sequence>
              <xs:element name="FIRST_NAME" type="xs:ID"></xs:element>
              <xs:element name="SURNAME" type="xs:string"></xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="UID" type="xs:IDREFS" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="DOCUMENTS">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DOCUMENT" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="DNAME" type="xs:ID"></xs:element>
                    <xs:element name="CREATE_DATE" type="xs:string"></xs:element>
                    <xs:element name="OWNER_ID" type="xs:IDREF"></xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="CHANGE_HISTORY" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DOCNAME" type="xs:IDREF"></xs:element>
              <xs:element name="USER_ID" type="xs:IDREF"></xs:element>
            <xs:element name="CHANGE_DATE" type="xs:date"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
      <xs:element name="OFFLINE_PRESENTATION" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DOCNAME" type="xs:IDREF"></xs:element>
              <xs:element name="PRESENTATION" type="xs:string"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== InvokerSoloMid/Kawaii/bd.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="XSLTFile.xsl"?>


<USERS-DOCUMENTS-CHANGE_HISTORY-OFFLINE_PRESENTATION
  xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com MyXMLSchema.xsd">
  <USERS>
    <USER>
      <NAME>
        <FIRST_NAME>Andrew</FIRST_NAME>
        <SURNAME>Iatskiv</SURNAME>
      </NAME>
      <UID>DOCUMENT_1</UID>
    </USER>
    <USER>
      <NAME>
        <FIRST_NAME>Yura</FIRST_NAME>
        <SURNAME>U2</SURNAME>
      </NAME>
      <UID>DOCUMENT_2</UID>
    </USER>
    <USER>
      <NAME>        
        <FIRST_NAME>Yaroslav</FIRST_NAME>
        <SURNAME>U3</SURNAME>
      </NAME>
      <UID>DOCUMENT_3</UID>
    </USER>
  </USERS>
  <DOCUMENTS>
    <DOCUMENT>
      <DNAME>DOCUMENT_1</DNAME>
      <CREATE_DATE>05.03.2019</CREATE_DATE>
      <OWNER_ID>Yura</OWNER_ID>
    </DOCUMENT>
    <DOCUMENT>
      <DNAME>DOCUMENT_2</DNAME>
      <CREATE_DATE>"04.03.2019"</CREATE_DATE>
      <OWNER_ID>Andrew</OWNER_ID>
    </DOCUMENT>
    <DOCUMENT>
      <DNAME>DOCUMENT_3</DNAME>
      <CREATE_DATE>"02.03.2019"</CREATE_DATE>
      <OWNER_ID>Yaroslav</OWNER_ID>
    </DOCUMENT>
  </DOCUMENTS>
  <CHANGE_HISTORY>
    <DOCNAME>DOCUMENT_1</DOCNAME>
    <USER_ID>Yura</USER_ID>
    <CHANGE_DATE>2019-01-01</CHANGE_DATE>
  </CHANGE_HISTORY>
  <CHANGE_HISTORY>
    <DOCNAME>DOCUMENT_2</DOCNAME>
    <USER_ID>Andrew</USER_ID>
    <CHANGE_DATE>2019-03-26</CHANGE_DATE>
  </CHANGE_HISTORY>
  <OFFLINE_PRESENTATION>
    <DOCNAME>DOCUMENT_1</DOCNAME>
    <PRESENTATION>ONLINE</PRESENTATION>
  </OFFLINE_PRESENTATION>
  <OFFLINE_PRESENTATION>
    <DOCNAME>DOCUMENT_2</DOCNAME>
    <PRESENTATION>FLASH</PRESENTATION>
  </OFFLINE_PRESENTATION>
  <OFFLINE_PRESENTATION>
    <DOCNAME>DOCUMENT_3</DOCNAME>
    <PRESENTATION>PAPER</PRESENTATION>
  </OFFLINE_PRESENTATION>
</USERS-DOCUMENTS-CHANGE_HISTORY-OFFLINE_PRESENTATION>

 <!--<!DOCTYPE USERS-DOCUMENT[ 
 <!ELEMENT USERS-DOCUMENT (USERS*, DOCUMENTS*)>
 <!ELEMENT USERS (USER*)>
 <!ELEMENT USER (NAME, UID)> 
 <!ATTLIST USER RANDOM ID #IMPLIED> 
 <!ELEMENT NAME (SURNAME, FIRST_NAME)> 
 <!ELEMENT SURNAME (#PCDATA)>
 <!ELEMENT FIRST_NAME (#PCDATA)>
 <!ELEMENT UID (#PCDATA)>
 <!ELEMENT DOCUMENTS (DOCUMENT*)>
 <!ELEMENT DOCUMENT (DNAME, CREATE_DATE, OWNER_ID)> 
 <!ATTLIST DOCUMENT DOCUMENTID ID #IMPLIED> 
 <!ELEMENT DNAME (#PCDATA)> 
 <!ELEMENT OWNER_ID (#PCDATA)> 
 <!ELEMENT CREATE_DATE (#PCDATA)> 
 ]>

<USERS-DOCUMENT>
  <USERS>
    <USER RANDOM="A1">
      <NAME>
        <SURNAME>U1</SURNAME>
        <FIRST_NAME>Andrew</FIRST_NAME>
      </NAME>

      <UID>DOCUMENT_1</UID>
    </USER>
    <USER RANDOM="A2">
      <NAME>
        <SURNAME>U2</SURNAME>
        <FIRST_NAME>Yura</FIRST_NAME>
      </NAME>
      <UID>DOCUMENT_2</UID>
    </USER>
    <USER RANDOM="A3">
      <NAME>
        <SURNAME>U3</SURNAME>
        <FIRST_NAME>Yaroslav</FIRST_NAME>
      </NAME>
      <UID>DOCUMENT_3</UID>
    </USER>
  </USERS>
  <DOCUMENTS>
    <DOCUMENT>
      <DNAME>DOCUMENT_1</DNAME>
      <CREATE_DATE>05.03.2019</CREATE_DATE>
      <OWNER_ID>USER_1</OWNER_ID>
    </DOCUMENT>
    <DOCUMENT>
      <DNAME>DOCUMENT_2</DNAME>
      <CREATE_DATE>"04.03.2019"</CREATE_DATE>
      <OWNER_ID>USER_2</OWNER_ID>
    </DOCUMENT>
    <DOCUMENT>
      <DNAME>DOCUMENT_3</DNAME>
      <CREATE_DATE>"02.03.2019"</CREATE_DATE>
      <OWNER_ID>USER_3</OWNER_ID>
    </DOCUMENT>
  </DOCUMENTS>
</USERS-DOCUMENT>-->
